ProjetoAlugar/Models/Aluguel.cs
namespace ProjetoAlugar.Models
{
    public class Aluguel
    {
        public int AluguelId { get; set; }

        public string UsuarioId { get; set; }

        public Usuario Usuario { get; set; }

        public int CarroId { get; set; }

        public Carro Carro { get; set; }

        public string Inicio { get; set; }

        public string Fim { get; set; }

        public int PrecoTotal { get; set; }
    }
}

ProjetoAlugar/Controllers/AluguelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProjetoAlugar.Interfaces;
using ProjetoAlugar.Models;
using ProjetoAlugar.Servicos;
using ProjetoAlugar.ViewsModels;

namespace ProjetoAlugar.Controllers
{
    [Authorize]
    public class AluguelController : Controller
    {
        private readonly IUsuario _usuarioRepositorio;
        private readonly IConta _contaRepositorio;
        private readonly IAluguel _aluguelRepositorio;
        private readonly IEmail _email;

        public AluguelController(
            IUsuario usuarioRepositorio,
            IConta contaRepositorio,
            IAluguel aluguelRepositorio,
            IEmail email
        )
        {
            _usuarioRepositorio = usuarioRepositorio;
            _contaRepositorio = contaRepositorio;
            _aluguelRepositorio = aluguelRepositorio;
            _email = email;
        }

        public IActionResult Aluguel(int carroId, int precoDiaria)
        {
            var aluguel = new AluguelViewModel
            {
                CarroId = carroId,
                PrecoDiaria = precoDiaria
            };

            return View(aluguel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Alugar(AluguelViewModel aluguel)
        {
            if (ModelState.IsValid)
            {
                var usuario = await _usuarioRepositorio.BuscarUsuarioLogado(User);
                var saldo = _contaRepositorio.BuscarSaldoPeloId(usuario.Id);

                if(await _aluguelRepositorio.VerificarReserva(usuario.Id, aluguel.CarroId, aluguel.Inicio, aluguel.Fim))
                {
                    TempData["Aviso"] = "Você já possui esse veículo";
                }
                else if (aluguel.PrecoTotal > saldo)
                {
                    TempData["Aviso"] = "Saldo insuficiente";
                }
                else
                {
                    Aluguel a = new Aluguel
                    {
                        UsuarioId = usuario.Id,
                        CarroId = aluguel.CarroId,
                        Inicio = aluguel.Inicio,
                        Fim = aluguel.Fim,
                        PrecoTotal = aluguel.PrecoTotal
                    };

                    //Enviar E-mail
                    string assunto = "Reserva concluída com sucesso";
                    string mensagem = string.Format("Seu veículo já o aguarda. Você poderá pegá-lo dia {0} e deverá devolvê-lo dia {1}. O preço será R${2},00. Divirtá-se !!! ", aluguel.Inicio, aluguel.Fim, aluguel.PrecoTotal);
                    //await _email.EnviarEmail(usuario.Email, assunto, mensagem);

                    //Insere aluguel no banco
                    await _aluguelRepositorio.Inserir(a);

                    //Altera saldo do usuário
                    var saldoUsuario = await _contaRepositorio.BuscarSaldoPeloUsuarioId(usuario.Id);
                    saldoUsuario.Saldo = saldoUsuario.Saldo - aluguel.PrecoTotal;
                    await _contaRepositorio.Atualizar(saldoUsuario);

                    return RedirectToAction("Index", "Carro");
                }
            }

            return View("Aluguel", aluguel);
        }
    }
}

ProjetoAlugar/ViewComponents/AluguelViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjetoAlugar.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProjetoAlugar.ViewComponents
{
    public class AluguelViewComponent : ViewComponent
    {
        private readonly Contexto _contexto;

        public AluguelViewComponent(Contexto contexto)
        {
            _contexto = contexto;
        }

        public async Task<IViewComponentResult> InvokeAsync(int CarroId)
        {
            return View(await _contexto.Carros.FirstOrDefaultAsync(c => c.CarroId == CarroId));
        }
    }
}

ProjetoAlugar/Views/Aluguel/Aluguel.cshtml
@model ProjetoAlugar.ViewsModels.AluguelViewModel

@{
    ViewData["Title"] = "Aluguel de Veículos";
}

@await Component.InvokeAsync("Aluguel", Model.CarroId)

<div class="row">
    <div class="col-md-4">
        @if(TempData["Aviso"] != null)
        {
            <p class="alert alert-warning">@TempData["Aviso"].ToString()</p>
        }

    <form asp-action="Alugar">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <input asp-for="CarroId" type="hidden" />

        <div class="form-group">
            <label asp-for="Inicio" class="control-label">Data Início</label>
            <input asp-for="Inicio" class="form-control datepicker" />
            <span asp-validation-for="Inicio" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Fim" class="control-label">Data Fim</label>
            <input asp-for="Fim" class="form-control datepicker" />
            <span asp-validation-for="Fim" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="PrecoDiaria" class="control-label">Preço Diária</label>
            <input asp-for="PrecoDiaria" class="form-control datepicker" id="precoDiaria" readonly />
            <span asp-validation-for="PrecoDiaria" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="PrecoTotal" class="control-label">Preço Total</label>
            <input asp-for="PrecoTotal" class="form-control datepicker" id="precoTotal" readonly/>
            <span asp-validation-for="PrecoTotal" class="text-danger"></span>
        </div>

        <div class="form-group float-right">
            <input type="submit" value="Salvar" class="btn btn-outline-success" />
            <a asp-action="Index" class="btn btn-outline-secondary">voltar</a>
        </div>
    </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
         $(".datepicker").datepicker({
            autoclose: true,
            calendarWeeks: true,
            clearBtn: true,
            todayBtn: true,
            todayHighlight: true,
            format: "dd/mm/yyyy",
            language: "pt-BR"
        })
        $("#Inicio").on('change', function () {
            if (($("#Inicio").val() !== "" && $("#Inicio").val() !== undefined) && ($("#Fim").val() !== "" && $("#Fim").val() !== undefined)) {
                var i = $("#Inicio").val().split("/");
                var inicio = new Date(i[2], i[1], i[0]);
                var f = $("#Fim").val().split("/");
                var fim = new Date(f[2], f[1], f[0]);
                var dias = ((fim - inicio) / 86400) / 1000;
                var precoDiaria = parseInt($("#precoDiaria").val());
                var precoTotal = precoDiaria * dias;
                
                $("#precoTotal").val(precoTotal);
            }
        });
        $("#Fim").on('change', function () {
            if (($("#Inicio").val() !== "" && $("#Inicio").val() !== undefined) && ($("#Fim").val() !== "" && $("#Fim").val() !== undefined)) {
                var i = $("#Inicio").val().split("/");
                var inicio = new Date(i[2], i[1], i[0]);
                var f = $("#Fim").val().split("/");
                var fim = new Date(f[2], f[1], f[0]);
                var dias = ((fim - inicio) / 86400) / 1000;
                
                var precoDiaria = parseInt($("#precoDiaria").val());
                var precoTotal = precoDiaria * dias;
               
                $("#precoTotal").val(precoTotal);
            }
        });
    </script>
}